### ISSUE TITLE
About the code in match_layer.py

### ISSUE THREAD

**Issue by ShawnWuzh** [baidu/DuReader#20]
In the class MatchLSTMAttnCell, the __call__ function, there is a tf.expand_dims(tc.layers.fully_connected(ref_vector,
                                                                   num_outputs=self._num_units,
                                                                   activation_fn=None), 1))
Why need to expand the dimension as axis 1?
Thx

**Comment by EastonWang** [comment]
This is the line:

`G = tf.tanh(self.fc_context + tf.expand_dims(tc.layers.fully_connected(ref_vector, num_outputs=self._num_units, activation_fn=None), 1))`

Here, the shape of `self.fc_context` is (batch_size, context_length, hidden_size), while the latter tensor after fully connected layer has its shape as (batch_size, hidden_size). So we need to expand the dimension of the latter tensor, otherwise we cannot add two tensors with different ranks.
