### ISSUE TITLE
problem of fake answer

### ISSUE THREAD

**Issue by susht3** [baidu/DuReader#3]
in util/preprocess.py

find_fake_answer(sample)

fake answer means bad answer in English, but i find it is selected as golden answer in your code. what does fake answer mean?

**Comment by comeonfox** [comment]
Thanks for your feedback. In the original dataset, we only have 'answers' field which contains golden answers, but most popular models need answer spans in passages, so we match golden answers with passages, and get the approximate spans (in most cases there is no exactly matched snippets in passages, because the golden answers are human generated according to question and multiple reference passages, not directly selected in certain passages), the "fake_answer" field is the snippet spanned by the approximate spans, and by 'fake' here we only want to express that this is not the golden answer, but is the closest answer we can find in passages compare to golden answers. I hope this explanation can clear your doubts.
