### ISSUE TITLE
how to achieve the baseline score

### ISSUE THREAD

**Issue by peanut8** [baidu/DuReader#4]
I see the method of choosing paragraph in tensorflow version is gold paragraph，should the score be more higher？thanks

**Comment by EastonWang** [comment]
@peanut8 The gold paragraph is only used during training. While in testing, the gold paragraph is actually not available since we don't know the answer.  So we calculate the `most_related_para` w.r.t the query. You can see [the lines 76~99 in `dataset.py`](https://github.com/baidu/DuReader/blob/b026efddfdcd625ce1507e2a52ac3bf6595e4716/tensorflow/dataset.py#L76) for more details.  This strategy is simple and you can try other strategies for better performance.
